// Action Types
export const CHAT_ACTIONS = {
  ADD_USER_MESSAGE: 'ADD_USER_MESSAGE',
  START_ASSISTANT_MESSAGE: 'START_ASSISTANT_MESSAGE',
  APPEND_ASSISTANT_CHUNK: 'APPEND_ASSISTANT_CHUNK',
  FINISH_ASSISTANT_MESSAGE: 'FINISH_ASSISTANT_MESSAGE',
  SET_ERROR: 'SET_ERROR',
  SET_STREAMING: 'SET_STREAMING',
  CLEAR_CHAT: 'CLEAR_CHAT',
}
