// Action Types
export const SOURCES_ACTIONS = {
  LOAD_DOCUMENTS_START: 'LOAD_DOCUMENTS_START',
  LOAD_DOCUMENTS_SUCCESS: 'LOAD_DOCUMENTS_SUCCESS',
  LOAD_DOCUMENTS_ERROR: 'LOAD_DOCUMENTS_ERROR',
  UPLOAD_START: 'UPLOAD_START',
  UPDATE_PROCESSING_STEP: 'UPDATE_PROCESSING_STEP',
  UPLOAD_SUCCESS: 'UPLOAD_SUCCESS',
  UPLOAD_ERROR: 'UPLOAD_ERROR',
  DELETE_DOCUMENT: 'DELETE_DOCUMENT',
  DELETE_ALL_DOCUMENTS: 'DELETE_ALL_DOCUMENTS',
}

// Processing Steps Definition
export const PROCESSING_STEPS = [
  'Saving document',
  'Chunking document',
  'Embedding document',
  'Complete',
]
