// Action Types for QA Container (Chat + Retrieval)
export const QA_ACTIONS = {
  // Chat Actions
  ADD_USER_MESSAGE: 'ADD_USER_MESSAGE',
  START_ASSISTANT_MESSAGE: 'START_ASSISTANT_MESSAGE',
  APPEND_ASSISTANT_CHUNK: 'APPEND_ASSISTANT_CHUNK',
  FINISH_ASSISTANT_MESSAGE: 'FINISH_ASSISTANT_MESSAGE',
  SET_CHAT_ERROR: 'SET_CHAT_ERROR',
  SET_STREAMING: 'SET_STREAMING',
  SET_MESSAGES_HISTORY: 'SET_MESSAGES_HISTORY',
  CLEAR_CHAT: 'CLEAR_CHAT',


  // Retrieval Actions
  START_RETRIEVAL: 'START_RETRIEVAL',
  SET_RETRIEVAL_CHUNKS: 'SET_RETRIEVAL_CHUNKS',
  SET_RETRIEVAL_ERROR: 'SET_RETRIEVAL_ERROR',
  CLEAR_RETRIEVAL: 'CLEAR_RETRIEVAL',
  TOGGLE_RETRIEVAL_GROUP: 'TOGGLE_RETRIEVAL_GROUP',
  FOCUS_RETRIEVAL_GROUP: 'FOCUS_RETRIEVAL_GROUP',


  // Connection Actions
  SET_CONNECTION_STATUS: 'SET_CONNECTION_STATUS',
}
